### ISSUE TITLE
ValueError: time data

### ISSUE THREAD

**Issue by Shaimaai** [ahmadamoudi/TwitterData#1]
Hi again Ahmed, 

I hope you are doing well. 

When I used your code to generate Twitter data from Arabic hashtag I got the following message: 
 
**ValueError: time data 'Wed Dec 16 08:22:59 +0000 2020' does not match format 'كوفيد١٩'**

If you do not mind, would you please help?

Regards

**Comment by ahmadamoudi** [comment]
Can you show me the code you use?

**Comment by ahmadamoudi** [comment]
Dear Shaimaa,

I noticed there is no need for couple of lines such as the below line for writing the file into CSV file.
`t['timestamp'] = datetime.datetime.strptime(t['created_at'], '%a %b %d %H:%M:%S +0000 %Y') `

So, I made changes in the code and now it should running without any issues.

check the jupyter notebook file in this link with sample data in CSV format:
https://github.com/ahmadamoudi/TwitterData/tree/master/CSV

you can check this link for the documentation of the same function I used in the code ([API.Search](http://docs.tweepy.org/en/latest/api.html#API.search))

Thank you for creating issue and to let me check the code and make it usable and works well.
